my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('my_blogs.urls')),
]

my_blogs/urls.py
from django.urls import path
from . import views

app_name = 'my_blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # page for adding new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL pattern for users"""

from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    # include default auth urls
    path('', include('django.contrib.auth.urls')),
    # registration page
    path('register/', views.register, name='register'),
]

my_blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'


    def __str__(self):
        return f"{self.text[:50]} ..."

users/models.py
from django.db import models

# Create your models here.

my_blogs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

my_blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    return render(request, 'my_blogs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'my_blogs/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'my_blogs/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        # Create blank form
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('my_blogs:topics')

    context = {'form': form}
    return render(request, 'my_blogs/new_topic.html', context)
    

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('my_blogs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'my_blogs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('my_blogs:topic', topic_id=topic.id)

    context ={'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'my_blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to homepage
            login(request, new_user)
            return redirect('my_blogs:index')

    # display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

my_blogs/templates/my_blogs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>My Blogs</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'my_blogs:index' %}">My Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_blogs:topics' %}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

my_blogs/templates/my_blogs/edit_entry.html
{% extends 'my_blogs/base.html' %}
{% block content %}

<p>
    <a href="{% url 'my_blogs:topic' topic.id %}">{{ topic }}</a>
</p>
<p>Edit Entry:</p>
<form action="{% url 'my_blogs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">save changes!</button>
</form>

{% endblock content %}

my_blogs/templates/my_blogs/index.html
{% extends 'my_blogs/base.html' %}
{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Hafidz Firdaus</h1>
    <p class="lead">is a Software Engineer</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

my_blogs/templates/my_blogs/new_entry.html
{% extends 'my_blogs/base.html' %}
{% block content %}

<p>
    <a href="{% url 'my_blogs:topic' topic.id %}">{{ topic }}</a>
</p>
<p>Add new entry:</p>
<form action="{% url 'my_blogs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add entry</button>
</form>

{% endblock content %}

my_blogs/templates/my_blogs/new_topic.html
{% extends 'my_blogs/base.html' %}
{% block content %}

<p>Add a new topic:</p>
<form action="{% url 'my_blogs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Topic</button>
</form>

{% endblock content %}

my_blogs/templates/my_blogs/topic.html
{% extends 'my_blogs/base.html' %}

{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}


{% block content %}

<p>Topic: {{ topic }}</p>
<p>Entries: </p>
<p>
    <a href="{% url 'my_blogs:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
    <div class="card mb-3">
        <h4 class="card-header">{{ entry.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'my_blogs:edit_entry' entry.id%}">Edit Entry</a></small>
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

my_blogs/templates/my_blogs/topics.html
{% extends 'my_blogs/base.html' %}

{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}

{% block content %}
<ul>
    {% for topic in topics %}
    <li><h3>
        <a href="{% url 'my_blogs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
    {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
</ul>
<h3><a href="{% url 'my_blogs:new_topic' %}">Add new topic</a></h3>
{% endblock content %}